
name: Deploy DotNet project to Azure Function App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'FunctionAppServerlessOpenHack'         
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'FunctionAppOH'                 
  DOTNET_VERSION: '3.1.x'                                         

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        ls -l ./output/
        popd
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: 'Archiving Package'
        path: './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        retention-days: 30
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
